"""added document.pages

Revision ID: 022503cf4bfa
Revises: f957f1cc8a70
Create Date: 2025-03-13 11:46:21.389310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022503cf4bfa'
down_revision: Union[str, None] = 'f957f1cc8a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pages', sa.Integer(), nullable=True), schema='paperless')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'pages', schema='paperless')
    # ### end Alembic commands ###
